import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to SunnyCoffeeShop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="px-0 text-blue-800">Hello, Haroun</h1>
      </main>
    </>
  );
}
